# The URL the site will be built for
base_url = "https://courses.fteychene.gihub.io"
theme = "adidoks"
title = "fteychene-learning"
description = "Courses and resources for learning for students"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"}, # Basic definition: no feed or pagination
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "fteychene"
github = "https://github.com/fteychene"
twitter = "https://twitter.com/fteychene"
email = "francois.teychene@gmail.com"

[extra.footer]
info = 'Powered by <a href="https://github.com/">Github</a>, <a href="https://www.getzola.org/">Zola</a>, and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'